/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_westalgo_factorycamera_supernight_DcsSupernight */

#ifndef _Included_com_westalgo_factorycamera_supernight_DcsSupernight
#define _Included_com_westalgo_factorycamera_supernight_DcsSupernight
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_westalgo_factorycamera_supernight_DcsSupernight
 * Method:    init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_westalgo_factorycamera_supernight_DcsSupernight_init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_westalgo_factorycamera_supernight_DcsSupernight
 * Method:    setParameters
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_westalgo_factorycamera_supernight_DcsSupernight_setParameters
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_westalgo_factorycamera_supernight_DcsSupernight
 * Method:    setImagePair
 * Signature: ([B[BIIIIII[B[BIIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_westalgo_factorycamera_supernight_DcsSupernight_setImagePair
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint, jint, jint, jint, jint, jbyteArray, jbyteArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_westalgo_factorycamera_supernight_DcsSupernight
 * Method:    generate
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_westalgo_factorycamera_supernight_DcsSupernight_generate
  (JNIEnv *, jclass, jbyteArray, jbyteArray);


JNIEXPORT jint Java_com_westalgo_factorycamera_supernight_DcsSupernight_unInit(JNIEnv *env, jclass thiz);


/*
 * Class:     com_westalgo_factorycamera_supernight_DcsSupernight
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_westalgo_factorycamera_supernight_DcsSupernight_getVersion
  (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
